<!doctype html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="./public/assets/css/styles.css">
    <link rel="icon" href="./public/assets/images/favicon.ico" type="image/ico" />
    <script src="https://kit.fontawesome.com/817262485e.js" crossorigin="anonymous"></script>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Get my new car</title>
</head>

<body>
    <div class="antialiased h-screen bg-gray-50 dark:bg-gray-900">
        <?php require './src/views/global/nav.phtml' ?>
        <?php require './src/views/global/sidebar.phtml' ?>

        <main class="p-4 md:ml-64 h-auto pt-20">

            <?php require './src/controllers/' . $route . '_controller.php'; ?>
        </main>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.2.4/howler.min.js"
        integrity="sha512-xi/RZRIF/S0hJ+yJJYuZ5yk6/8pCiRlEXZzoguSMl+vk2i3m6UjUO/WcZ11blRL/O+rnj94JRGwt/CHbc9+6EA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
    <script src="./src/scripts/script.js"></script>
</body>

</html>